apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    name: redis
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
      app: demo-voting-app

  template:
    metadata:
      name: redis
      labels:
        name: redis
        app: demo-voting-app
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service-upstreams': 'worker-app:80'
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379

